import type { Metadata } from 'next';

import './globals.css';
import DynamicBackground from '@/app/blog/components/DynamicBackground';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <DynamicBackground />
          {children}
        </main>
      </body>
    </html>
  );
}
